// SPDX-License-Identifier: Apache-2.0
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.0. SEE SOURCE BELOW. !!
pragma solidity >=0.5.0;

interface IPFS {
    event Register(string addr, address eaddr);

    function addNode(bytes calldata ipfsAddress) external;

    function getNodes() external view returns (bytes memory);

    function initialize(address _purchase) external;

    function register(string calldata addr) external;

    function resetNodes() external;
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"addr","type":"string"},{"indexed":false,"internalType":"address","name":"eaddr","type":"address"}],"name":"Register","type":"event"},{"inputs":[{"internalType":"bytes","name":"ipfsAddress","type":"bytes"}],"name":"addNode","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"getNodes","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_purchase","type":"address"}],"name":"initialize","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"addr","type":"string"}],"name":"register","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"resetNodes","outputs":[],"stateMutability":"nonpayable","type":"function"}]
*/
